export const projects = [
  {
    num: "01",
    category: "Full Stack",
    title: "Admin Dashboard",
    description:
      "In this project I built and deployed a MERN Stack Admin Dashboard. For the frontend, I used Material UI, Material UI Data Grid, Nivo Charts, Redux Toolkit and Redux Toolkit Query. For backend, I used Node JS, Express Js, Mongoose, and MongoDB.",
    stack: [
      { name: "JavaScript" },
      { name: "Material UI" },
      { name: "Redux Toolkit" },
      { name: "Node.js" },
      { name: "Express.js" },
      { name: "MongoDB" },
    ],
    image: "/assets/work/project1.png",
    link: "https://mern-dashboard-client-37t0.onrender.com",
    github: "https://github.com/Besufekad-HAZ/MERN-Admin-Dashboard",
  },
  {
    num: "02",
    category: "Full Stack",
    title: "Ezra Seminary",
    description:
      "Ezra Seminary is a MERN stack Learning Management System (LMS) app to study the Bible online, get daily devotions, and study the quarterly Sabbath school.",
    stack: [
      { name: "HTML5" },
      { name: "CSS3" },
      { name: "TypeScript" },
      { name: "React" },
      { name: "Node.js" },
      { name: "Express.js" },
      { name: "MongoDB" },
    ],
    image: "/assets/work/project2.png",
    link: "https://ezraseminary.org",
    github: "https://github.com/EzraSeminary",
  },
  {
    num: "03",
    category: "Full Stack",
    title: "Hope Channel Ethiopia",
    description:
      "Hope Channel Ethiopia is a modern Christian broadcasting website featuring live streaming, on-demand content, interactive schedules, and community tools. It supports multiple languages and offers a seamless experience for spiritual engagement.",
    stack: [
      { name: "Next.js 15" },
      { name: "React 19" },
      { name: "TypeScript" },
      { name: "Tailwind CSS" },
      { name: "Shadcn/ui" },
      { name: "Node.js" },
      { name: "YouTube API" },
      { name: "Mapbox GL" },
      { name: "Lucide React" },
      { name: "React Hook Form" },
      { name: "Zod Validation" },
      { name: "Framer Motion" },
    ],
    image: "/assets/work/hope.png",
    link: "https://hopechannelethiopia.org/",
    github: "https://github.com/Besufekad-HAZ/Hope-channel-ethiopia",
  },
  {
    num: "04",
    category: "Full Stack",
    title: "Ethio-Chat",
    description:
      "A full stack chat application built with React JS and Firebase. Users can create accounts, chat with friends, and send images. Authentication is handled by Firebase, chat images are stored in Firebase Storage, and messages are stored in Firestore Database for real-time updates.",
    stack: [
      { name: "React (Front-end)" },
      { name: "Firebase (Back-end)" },
      { name: "CSS3" },
      { name: "JavaScript" },
      { name: "Firebase Storage for image uploads" },
    ],
    image: "/assets/work/chat-app.png",
    link: "https://chat-app-7q7.pages.dev",
    github: "https://github.com/Besufekad-HAZ/Chat-App",
  },
  {
    num: "05",
    category: "Full Stack",
    title: "Url Shortener",
    description:
      "URL shortener is a web application that takes a long URL and generates a shorter, unique URL that redirects to the original URL. This is useful for sharing long links, especially on platforms with character limits like social media.",
    stack: [
      { name: "Ruby on Rails" },
      { name: "PostgreSQL" },
      { name: "HTML5" },
      { name: "CSS3" },
      { name: "JavaScript" },
      { name: "Heroku" },
      { name: "GitHub Actions" },
    ],
    image: "/assets/work/project3.png",
    link: "https://url-shortner-bese-b983225bbc35.herokuapp.com/",
    github: "https://github.com/Besufekad-HAZ/URL-shortener",
  },
  {
    num: "06",
    category: "Full Stack",
    title: "Background removal",
    description:
      "Bg-removal is a versatile image editing tool built with the MERN stack. Upload an image, let our AI process it, and download the image with a transparent background. Experience seamless background removal and manage your credits with integrated online payment.",
    stack: [
      { name: "MongoDB" },
      { name: "Express" },
      { name: "React" },
      { name: "Node.js" },
      { name: "Clerk" },
      { name: "JavaScript" },
      { name: "HTML5" },
      { name: "CSS3" },
    ],
    image: "/assets/work/bg-removal.png",
    link: "https://background-remover-app-ovof.vercel.app",
    github: "https://github.com/Besufekad-HAZ/background-remover-app",
  },
  {
    num: "07",
    category: "Full Stack",
    title: "Motorcycle Rental Store",
    description:
      "This project is for reserving motorcycles. Whether you're gearing up for a special occasion or event and need a trendy scooter, or if you own a luxurious Vespa and want to earn extra income by renting it out, our website is your ideal destination. Key features include user registration, motorcycle reservations, and the ability to list and manage your own Vespas for rent.",
    stack: [
      { name: "Ruby on Rails" },
      { name: "PostgreSQL" },
      { name: "HTML5" },
      { name: "CSS3" },
      { name: "JavaScript" },
      { name: "React" },
      { name: "Redux" },
      { name: "Render" },
      { name: "GitHub Actions" },
    ],
    image: "/assets/work/project4.png",
    link: "https://rent-motorcycles.onrender.com",
    github: "https://github.com/TamaraDimov/vespa-rentals-frontend",
  },
  {
    num: "08",
    category: "Front End",
    title: "Air Pollution Data Web App",
    description:
      "Air-Pollution-Data is a React Capstone Project that provides a simple interface for quickly displaying Air pollution data for different countries. In addition, it provides current, forecast, and historical air pollution data for any coordinates on the globe.",
    stack: [
      { name: "HTML5" },
      { name: "CSS3" },
      { name: "JavaScript" },
      { name: "Webpack" },
      { name: "React" },
      { name: "Redux" },
      { name: "Redux Toolkit" },
    ],
    image: "/assets/work/project6.png",
    link: "https://airpollution-seven.vercel.app",
    github: "https://github.com/Besufekad-HAZ/React-Capstone-Air-Pollution",
  },
  {
    num: "09",
    category: "Full Stack",
    title: "AI Code Reviewer",
    description:
      "AI Code Reviewer is an intelligent web application that provides automated code reviews using artificial intelligence. Developers can paste their code into the editor and receive instant feedback on code quality, potential bugs, and best practices.",
    stack: [
      { name: "React.js" },
      { name: "react-simple-code-editor" },
      { name: "Prism.js" },
      { name: "CSS3" },
      { name: "react-markdown" },
    ],
    image:
      "https://www.tabnine.com/wp-content/uploads/2023/10/AI-Code-Review.png.webp",
    link: "https://ai-codereview.netlify.app",
    github: "https://github.com/Besufekad-HAZ/AI-CodeReview",
  },
];
